### ISSUE TITLE
why not use official NaughtyAttributes as dependance?

### ISSUE THREAD

**Issue by filod** [peeweek/net.peeweek.gameplay-ingredients#24]
it conflict with NaughtyAttributes package.

**Comment by RamType0** [comment]
AFIK, dependency to git or local packages will not be resolved automatically.

**Comment by peeweek** [comment]
Hello, some news about this. 

I am currently underway making it a dependency, but I had first to make a PR to NaughtyAttributes to fix the rendering of reorderable lists drawing property drawers. The PR has been merged in a v2 branch for now and is awaiting a new package release. If I understand correctly, NaughtyAttributes will have a v2 soon, then a release on OpenUPM.

When it's ready, I will do the change ASAP for GPI which means some radical changes to the install method (probably gonna change the major version to 2020 as well):
- Change to Minimal version: 2020.1
- UPM install only, requiring url `https://package.openupm.com` and `net.peeweek` and `com.dbrizov` scopes
- Will also remove redundant features (eg: new scene from template) for 2020.2 and newer


Long term considerations:
- If the built-in UX improves, using the new default list UX instead of ReorderableLists (I will keep NaughtyAttributes because there are some other useful PropertyDrawers I use)

**Comment by peeweek** [comment]
I have published the new 2020.2.0 version, which relies on OpenUPM packages. However, due to a bug in Unity 2020.2, the package manager currently does not display the option to select custom registries in package manager (should be solved in 2020.2.3f1)

in the meantime, you can define the package version in you `manifest.json`
